// Generated by `wit-bindgen` 0.39.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System.Runtime.InteropServices;

namespace ImportsWorld.wit.imports.wasi.clocks.v0_2_1
{
    public static class MonotonicClockInterop {

        internal static class NowWasmInterop
        {
            [DllImport("wasi:clocks/monotonic-clock@0.2.1", EntryPoint = "now"), WasmImportLinkage]
            internal static extern long wasmImportNow();
        }

        public  static unsafe ulong Now()
        {
            var result =  NowWasmInterop.wasmImportNow();
            return unchecked((ulong)(result));

        }

        internal static class ResolutionWasmInterop
        {
            [DllImport("wasi:clocks/monotonic-clock@0.2.1", EntryPoint = "resolution"), WasmImportLinkage]
            internal static extern long wasmImportResolution();
        }

        public  static unsafe ulong Resolution()
        {
            var result =  ResolutionWasmInterop.wasmImportResolution();
            return unchecked((ulong)(result));

        }

        internal static class SubscribeInstantWasmInterop
        {
            [DllImport("wasi:clocks/monotonic-clock@0.2.1", EntryPoint = "subscribe-instant"), WasmImportLinkage]
            internal static extern int wasmImportSubscribeInstant(long p0);
        }

        public  static unsafe global::ImportsWorld.wit.imports.wasi.io.v0_2_1.IPoll.Pollable SubscribeInstant(ulong when)
        {
            var result =  SubscribeInstantWasmInterop.wasmImportSubscribeInstant(unchecked((long)(when)));
            var resource = new global::ImportsWorld.wit.imports.wasi.io.v0_2_1.IPoll.Pollable(new global::ImportsWorld.wit.imports.wasi.io.v0_2_1.IPoll.Pollable.THandle(result));
            return resource;

        }

        internal static class SubscribeDurationWasmInterop
        {
            [DllImport("wasi:clocks/monotonic-clock@0.2.1", EntryPoint = "subscribe-duration"), WasmImportLinkage]
            internal static extern int wasmImportSubscribeDuration(long p0);
        }

        public  static unsafe global::ImportsWorld.wit.imports.wasi.io.v0_2_1.IPoll.Pollable SubscribeDuration(ulong when)
        {
            var result =  SubscribeDurationWasmInterop.wasmImportSubscribeDuration(unchecked((long)(when)));
            var resource = new global::ImportsWorld.wit.imports.wasi.io.v0_2_1.IPoll.Pollable(new global::ImportsWorld.wit.imports.wasi.io.v0_2_1.IPoll.Pollable.THandle(result));
            return resource;

        }

    }
}
