// Generated by `wit-bindgen` 0.39.0. DO NOT EDIT!
// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Text;
using System.Collections.Generic;
namespace ImportsWorld.wit.imports.wasi.tls.v0_2_1;

public interface ITypes {

    public class ClientHandshake: IDisposable {
        internal int Handle { get; set; }

        public readonly record struct THandle(int Handle);

        public ClientHandshake(THandle handle) {
            Handle = handle.Handle;
        }

        public void Dispose() {
            Dispose(true);
        }

        [DllImport("wasi:tls/types@0.2.1", EntryPoint = "[resource-drop]client-handshake"), WasmImportLinkage]
        private static extern void wasmImportResourceDrop(int p0);

        protected virtual void Dispose(bool disposing) {
            if (disposing && Handle != 0) {
                wasmImportResourceDrop(Handle);
                Handle = 0;
            }
        }

        internal static class ConstructorWasmInterop
        {
            [DllImport("wasi:tls/types@0.2.1", EntryPoint = "[constructor]client-handshake"), WasmImportLinkage]
            internal static extern int wasmImportConstructor(nint p0, int p1, int p2, int p3);
        }

        public   unsafe  ClientHandshake(string serverName, global::ImportsWorld.wit.imports.wasi.io.v0_2_1.IStreams.InputStream input, global::ImportsWorld.wit.imports.wasi.io.v0_2_1.IStreams.OutputStream output)
        {
            var cleanups = new List<Action>();

            var utf8Bytes = Encoding.UTF8.GetBytes(serverName);
            var length = utf8Bytes.Length;
            var gcHandle = GCHandle.Alloc(utf8Bytes, GCHandleType.Pinned);
            var interopString = gcHandle.AddrOfPinnedObject();

            cleanups.Add(()=> gcHandle.Free());
            var handle = input.Handle;
            input.Handle = 0;
            var handle0 = output.Handle;
            output.Handle = 0;
            var result =  ConstructorWasmInterop.wasmImportConstructor(interopString.ToInt32(), length, handle, handle0);
            this.Handle = result;

            foreach (var cleanup in cleanups)
            {
                cleanup();
            }

        }

        internal static class FinishWasmInterop
        {
            [DllImport("wasi:tls/types@0.2.1", EntryPoint = "[static]client-handshake.finish"), WasmImportLinkage]
            internal static extern int wasmImportFinish(int p0);
        }

        public  static unsafe global::ImportsWorld.wit.imports.wasi.tls.v0_2_1.ITypes.FutureClientStreams Finish(global::ImportsWorld.wit.imports.wasi.tls.v0_2_1.ITypes.ClientHandshake @this)
        {
            var handle = @this.Handle;
            @this.Handle = 0;
            var result =  FinishWasmInterop.wasmImportFinish(handle);
            var resource = new global::ImportsWorld.wit.imports.wasi.tls.v0_2_1.ITypes.FutureClientStreams(new global::ImportsWorld.wit.imports.wasi.tls.v0_2_1.ITypes.FutureClientStreams.THandle(result));
            return resource;

        }

    }

    public class ClientConnection: IDisposable {
        internal int Handle { get; set; }

        public readonly record struct THandle(int Handle);

        public ClientConnection(THandle handle) {
            Handle = handle.Handle;
        }

        public void Dispose() {
            Dispose(true);
        }

        [DllImport("wasi:tls/types@0.2.1", EntryPoint = "[resource-drop]client-connection"), WasmImportLinkage]
        private static extern void wasmImportResourceDrop(int p0);

        protected virtual void Dispose(bool disposing) {
            if (disposing && Handle != 0) {
                wasmImportResourceDrop(Handle);
                Handle = 0;
            }
        }

        internal static class CloseNotifyWasmInterop
        {
            [DllImport("wasi:tls/types@0.2.1", EntryPoint = "[method]client-connection.close-notify"), WasmImportLinkage]
            internal static extern void wasmImportCloseNotify(int p0, nint p1);
        }

        public   unsafe Result<None, global::ImportsWorld.wit.imports.wasi.io.v0_2_1.IError.Error>? CloseNotify()
        {
            var handle = this.Handle;

            var retArea = stackalloc uint[3+1];
            var ptr = ((int)retArea) + (4 - 1) & -4;
            CloseNotifyWasmInterop.wasmImportCloseNotify(handle, ptr);

            Result<None, global::ImportsWorld.wit.imports.wasi.io.v0_2_1.IError.Error>? lifted6;

            switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                case 0: {
                    lifted6 = null;
                    break;
                }

                case 1: {

                    Result<None, global::ImportsWorld.wit.imports.wasi.io.v0_2_1.IError.Error> lifted;

                    switch (new Span<byte>((void*)(ptr + 4), 1)[0]) {
                        case 0: {

                            lifted = Result<None, global::ImportsWorld.wit.imports.wasi.io.v0_2_1.IError.Error>.Ok(new global::ImportsWorld.None());
                            break;
                        }
                        case 1: {
                            var resource = new global::ImportsWorld.wit.imports.wasi.io.v0_2_1.IError.Error(new global::ImportsWorld.wit.imports.wasi.io.v0_2_1.IError.Error.THandle(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4))));

                            lifted = Result<None, global::ImportsWorld.wit.imports.wasi.io.v0_2_1.IError.Error>.Err(resource);
                            break;
                        }

                        default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 4), 1)[0]}");
                    }

                    lifted6 = lifted;
                    break;
                }

                default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 0), 1)[0]));
            }
            return lifted6;

        }

    }

    public class FutureClientStreams: IDisposable {
        internal int Handle { get; set; }

        public readonly record struct THandle(int Handle);

        public FutureClientStreams(THandle handle) {
            Handle = handle.Handle;
        }

        public void Dispose() {
            Dispose(true);
        }

        [DllImport("wasi:tls/types@0.2.1", EntryPoint = "[resource-drop]future-client-streams"), WasmImportLinkage]
        private static extern void wasmImportResourceDrop(int p0);

        protected virtual void Dispose(bool disposing) {
            if (disposing && Handle != 0) {
                wasmImportResourceDrop(Handle);
                Handle = 0;
            }
        }

        internal static class SubscribeWasmInterop
        {
            [DllImport("wasi:tls/types@0.2.1", EntryPoint = "[method]future-client-streams.subscribe"), WasmImportLinkage]
            internal static extern int wasmImportSubscribe(int p0);
        }

        public   unsafe global::ImportsWorld.wit.imports.wasi.io.v0_2_1.IPoll.Pollable Subscribe()
        {
            var handle = this.Handle;
            var result =  SubscribeWasmInterop.wasmImportSubscribe(handle);
            var resource = new global::ImportsWorld.wit.imports.wasi.io.v0_2_1.IPoll.Pollable(new global::ImportsWorld.wit.imports.wasi.io.v0_2_1.IPoll.Pollable.THandle(result));
            return resource;

        }

        internal static class GetWasmInterop
        {
            [DllImport("wasi:tls/types@0.2.1", EntryPoint = "[method]future-client-streams.get"), WasmImportLinkage]
            internal static extern void wasmImportGet(int p0, nint p1);
        }

        public   unsafe Result<Result<(global::ImportsWorld.wit.imports.wasi.tls.v0_2_1.ITypes.ClientConnection, global::ImportsWorld.wit.imports.wasi.io.v0_2_1.IStreams.InputStream, global::ImportsWorld.wit.imports.wasi.io.v0_2_1.IStreams.OutputStream), None>, None>? Get()
        {
            var handle = this.Handle;

            var retArea = stackalloc uint[6+1];
            var ptr = ((int)retArea) + (4 - 1) & -4;
            GetWasmInterop.wasmImportGet(handle, ptr);

            Result<Result<(global::ImportsWorld.wit.imports.wasi.tls.v0_2_1.ITypes.ClientConnection, global::ImportsWorld.wit.imports.wasi.io.v0_2_1.IStreams.InputStream, global::ImportsWorld.wit.imports.wasi.io.v0_2_1.IStreams.OutputStream), None>, None>? lifted13;

            switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                case 0: {
                    lifted13 = null;
                    break;
                }

                case 1: {

                    Result<Result<(global::ImportsWorld.wit.imports.wasi.tls.v0_2_1.ITypes.ClientConnection, global::ImportsWorld.wit.imports.wasi.io.v0_2_1.IStreams.InputStream, global::ImportsWorld.wit.imports.wasi.io.v0_2_1.IStreams.OutputStream), None>, None> lifted12;

                    switch (new Span<byte>((void*)(ptr + 4), 1)[0]) {
                        case 0: {

                            Result<(global::ImportsWorld.wit.imports.wasi.tls.v0_2_1.ITypes.ClientConnection, global::ImportsWorld.wit.imports.wasi.io.v0_2_1.IStreams.InputStream, global::ImportsWorld.wit.imports.wasi.io.v0_2_1.IStreams.OutputStream), None> lifted;

                            switch (new Span<byte>((void*)(ptr + 8), 1)[0]) {
                                case 0: {
                                    var resource = new global::ImportsWorld.wit.imports.wasi.tls.v0_2_1.ITypes.ClientConnection(new global::ImportsWorld.wit.imports.wasi.tls.v0_2_1.ITypes.ClientConnection.THandle(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 12), 4))));
                                    var resource6 = new global::ImportsWorld.wit.imports.wasi.io.v0_2_1.IStreams.InputStream(new global::ImportsWorld.wit.imports.wasi.io.v0_2_1.IStreams.InputStream.THandle(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 16), 4))));
                                    var resource7 = new global::ImportsWorld.wit.imports.wasi.io.v0_2_1.IStreams.OutputStream(new global::ImportsWorld.wit.imports.wasi.io.v0_2_1.IStreams.OutputStream.THandle(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 20), 4))));

                                    lifted = Result<(global::ImportsWorld.wit.imports.wasi.tls.v0_2_1.ITypes.ClientConnection, global::ImportsWorld.wit.imports.wasi.io.v0_2_1.IStreams.InputStream, global::ImportsWorld.wit.imports.wasi.io.v0_2_1.IStreams.OutputStream), None>.Ok((resource, resource6, resource7));
                                    break;
                                }
                                case 1: {

                                    lifted = Result<(global::ImportsWorld.wit.imports.wasi.tls.v0_2_1.ITypes.ClientConnection, global::ImportsWorld.wit.imports.wasi.io.v0_2_1.IStreams.InputStream, global::ImportsWorld.wit.imports.wasi.io.v0_2_1.IStreams.OutputStream), None>.Err(new global::ImportsWorld.None());
                                    break;
                                }

                                default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 8), 1)[0]}");
                            }

                            lifted12 = Result<Result<(global::ImportsWorld.wit.imports.wasi.tls.v0_2_1.ITypes.ClientConnection, global::ImportsWorld.wit.imports.wasi.io.v0_2_1.IStreams.InputStream, global::ImportsWorld.wit.imports.wasi.io.v0_2_1.IStreams.OutputStream), None>, None>.Ok(lifted);
                            break;
                        }
                        case 1: {

                            lifted12 = Result<Result<(global::ImportsWorld.wit.imports.wasi.tls.v0_2_1.ITypes.ClientConnection, global::ImportsWorld.wit.imports.wasi.io.v0_2_1.IStreams.InputStream, global::ImportsWorld.wit.imports.wasi.io.v0_2_1.IStreams.OutputStream), None>, None>.Err(new global::ImportsWorld.None());
                            break;
                        }

                        default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 4), 1)[0]}");
                    }

                    lifted13 = lifted12;
                    break;
                }

                default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 0), 1)[0]));
            }
            return lifted13;

        }

    }

}
