// Generated by `wit-bindgen` 0.39.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Text;

namespace ImportsWorld.wit.imports.wasi.sockets.v0_2_1
{
    public static class IpNameLookupInterop {

        internal static class ResolveAddressesWasmInterop
        {
            [DllImport("wasi:sockets/ip-name-lookup@0.2.1", EntryPoint = "resolve-addresses"), WasmImportLinkage]
            internal static extern void wasmImportResolveAddresses(int p0, nint p1, int p2, nint p3);
        }

        public  static unsafe global::ImportsWorld.wit.imports.wasi.sockets.v0_2_1.IIpNameLookup.ResolveAddressStream ResolveAddresses(global::ImportsWorld.wit.imports.wasi.sockets.v0_2_1.INetwork.Network network, string name)
        {
            var cleanups = new List<Action>();
            var handle = network.Handle;

            var utf8Bytes = Encoding.UTF8.GetBytes(name);
            var length = utf8Bytes.Length;
            var gcHandle = GCHandle.Alloc(utf8Bytes, GCHandleType.Pinned);
            var interopString = gcHandle.AddrOfPinnedObject();

            cleanups.Add(()=> gcHandle.Free());

            var retArea = stackalloc uint[2+1];
            var ptr = ((int)retArea) + (4 - 1) & -4;
            ResolveAddressesWasmInterop.wasmImportResolveAddresses(handle, interopString.ToInt32(), length, ptr);

            Result<global::ImportsWorld.wit.imports.wasi.sockets.v0_2_1.IIpNameLookup.ResolveAddressStream, global::ImportsWorld.wit.imports.wasi.sockets.v0_2_1.INetwork.ErrorCode> lifted;

            switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                case 0: {
                    var resource = new global::ImportsWorld.wit.imports.wasi.sockets.v0_2_1.IIpNameLookup.ResolveAddressStream(new global::ImportsWorld.wit.imports.wasi.sockets.v0_2_1.IIpNameLookup.ResolveAddressStream.THandle(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4))));

                    lifted = Result<global::ImportsWorld.wit.imports.wasi.sockets.v0_2_1.IIpNameLookup.ResolveAddressStream, global::ImportsWorld.wit.imports.wasi.sockets.v0_2_1.INetwork.ErrorCode>.Ok(resource);
                    break;
                }
                case 1: {

                    lifted = Result<global::ImportsWorld.wit.imports.wasi.sockets.v0_2_1.IIpNameLookup.ResolveAddressStream, global::ImportsWorld.wit.imports.wasi.sockets.v0_2_1.INetwork.ErrorCode>.Err((global::ImportsWorld.wit.imports.wasi.sockets.v0_2_1.INetwork.ErrorCode)new Span<byte>((void*)(ptr + 4), 1)[0]);
                    break;
                }

                default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
            }

            foreach (var cleanup in cleanups)
            {
                cleanup();
            }
            if (lifted.IsOk)
            {
                var tmp = lifted.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::ImportsWorld.wit.imports.wasi.sockets.v0_2_1.INetwork.ErrorCode>(lifted.AsErr!, 0);
            }

        }

    }
}
